[package]
name = "bhwi"
version = "0.0.1"
edition = "2021"
authors = ["Edouard Paris <m@edouard.paris>"]
repository = "https://github.com/wizardsardine/bhwi"
license-file = "LICENSE"
keywords = ["bitcoin",  "miniscript"]
description = "development kit"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["jade"]
jade = ["serde", "serde_bytes", "serde_cbor"]

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = "1.0.121"
serde_bytes = { version = "0.11.14", optional = true }
serde_cbor = { version = "0.11", optional = true }
bitcoin = "0.32.2"

# TODO: remove me
log = "0.4"
